[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "addition_mod"
version = "0.0.1"
dependencies = [
    "joblib==1.2.0",
    "pandas==2.2.0",
    "scikit_learn==1.3.0",
    "scipy==1.12.0",
    "six==1.16.0",
    "argparse",
    "mlflow"
]
