name: CI/CD-Workshop

on:
  push:
    branches:
      - ci-helloworld
  workflow_dispatch:

jobs:

  checkout-job-runs:
    name: With Checkout
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Installing tree
        run: |
          sudo apt-get install -y tree
          tree .

  without-checkout-job-runs:
    name: Without Checkout
    runs-on: 'ubuntu-latest'
    steps:
      - name: Run ls
        run: |
          ls -la

      - name: Installing tree
        run: |
          sudo apt-get install -y tree
          tree .
