# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Building and Deploying py-package

on:
  push:
    branches:
      - ci-py-package
  workflow_dispatch:

jobs:

  conda-runs:
    name: Build py-package
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: SetUp Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip list

      - name: BashCMD - ls
        shell: bash -el {0}
        run: |
          ls -la
