# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Building and Deploying py-package

on:
  push:
    branches:
      - ci-py-package
  workflow_dispatch:

jobs:

  build-runs:
    name: Build py-package
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: SetUp Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip list

      - name: Installing tree
        shell: bash -el {0}
        run: |
          sudo apt-get install -y tree

      - name: BashCMD - ls (before)
        shell: bash -el {0}
        run: |
          ls -la
          tree .

      - name: Upgrade and build
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: BashCMD - ls (after)
        shell: bash -el {0}
        run: |
          ls -la
          tree .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-build
          path: dist/

  deploy-runs:
    name: Download and run py-package
    runs-on: 'ubuntu-latest'
    needs: build-runs
    steps:
      - name: Installing tree
        shell: bash -el {0}
        run: |
          sudo apt-get install -y tree

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-build

      - name: BashCMD - ls (before unzip)
        shell: bash -el {0}
        run: |
          ls -la
          tree .

      - name: Install package
        run: |
          pip install addition_mod-0.0.1-py3-none-any.whl

      - name: Run package
        run: |
          python -c "from addition_mod import adder; print(adder.add_one(2))"
     